
import { ClerkProvider } from "@clerk/nextjs";
import { dark as darkTheme } from "@clerk/themes";
import { useTheme } from "next-themes";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import AuthProvider from "@/providers/auth-provider";
import Provider from "./provider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <AuthProvider>
          <NextThemesProvider attribute="class" defaultTheme="dark">
            <Provider>{children}</Provider>
          </NextThemesProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
